version: "3.8"

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=password123
      - REDIS_PORT_NUMBER=7000
    networks:
      - default
    ports:
    - '7000:7000'
  
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
      - redis
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data: